services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.8.14.6-alpine
    volumes:
      - ./data/ch:/var/lib/clickhouse/
      - ./data/ch-server:/var/log/clickhouse-server/
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - 9000:9000/tcp
      - 8123:8123/tcp
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000/tcp
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ADMIN_USER: admin
      GF_INSTALL_PLUGINS: vertamedia-clickhouse-datasource
      
