name: Schedule

on:
  schedule:
    - cron: '5 10 * * *'

jobs:
  save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate files
        run: python -u ./sm.py

      - name: commit csv files to main
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "CI"
          git fetch
          git branch -a
          git checkout main
          git add .
          git commit -m "Update csv files"
          git push
